name: next_app
description: A Flutter application template. 

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  connectivity: ^2.0.2
  cupertino_icons: ^1.0.1
  dio: ^3.0.10
  equatable: ^1.2.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.16.1
  kiwi: ^2.1.1

dev_dependencies:
  flutter_launcher_icons: ^0.8.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  intl_translation: ^0.17.10+1
  lint: ^1.5.1
  mockito: ^4.1.3

dependency_overrides:
  analyzer: 0.40.6
  intl: ^0.17.0-nullsafety.2

flutter:

  uses-material-design: true

  assets:
    - resources/fonts/
    - resources/images/
    - resources/animations/

  fonts:
    - family: Roboto
      fonts:
        - asset: resources/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: resources/fonts/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: resources/fonts/Roboto-Light.ttf
          weight: 300
        - asset: resources/fonts/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: resources/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: resources/fonts/Roboto-Italic.ttf
          style: italic
        - asset: resources/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: resources/fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: resources/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: resources/fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: resources/fonts/Roboto-Black.ttf
          weight: 900
        - asset: resources/fonts/Roboto-BlackItalic.ttf
          weight: 900
          style: italic

flutter_intl:
  enabled: true
  arb_dir: lib/presentation/localization/translations
  output_dir: lib/presentation/localization/generated
